env:
  # Expected environment variables (not stored in git)
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
  OLLAMA_HOST: ${OLLAMA_HOST}

agent:
  preset: ../agents/default.yaml

runtime:
  approvals: on-request
  network: restricted
  fs: workspace-write
