env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  # Optional: n8n API credentials (if using API-driven workflows in tools)
  N8N_BASE_URL: ${N8N_BASE_URL}
  N8N_API_KEY: ${N8N_API_KEY}

agent:
  preset: ../agents/n8n.yaml

runtime:
  approvals: on-request
  network: restricted
  fs: workspace-write

# MCP Server Configuration
mcp:
  servers:
    n8n-mcp:
      type: stdio
      command: npx
      args:
        - n8n-mcp
      env:
        N8N_API_URL: https://n8n.srv1068954.hstgr.cloud
        N8N_API_KEY: ${N8N_API_KEY}
        MCP_MODE: stdio
        LOG_LEVEL: error
        DISABLE_CONSOLE_OUTPUT: "true"

